# Generated by Django 3.2.5 on 2021-09-15 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lieu_de_travail', '0004_auto_20210807_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu_de_travail',
            name='commissariat_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lieu_de_travail.commissariat_de_police'),
        ),
        migrations.AlterField(
            model_name='lieu_de_travail',
            name='province_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lieu_de_travail.province'),
        ),
        migrations.AlterField(
            model_name='lieu_de_travail',
            name='region_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lieu_de_travail.region'),
        ),
    ]
