# Generated by Django 3.1.7 on 2021-07-18 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lieu_de_travail', '0001_initial'),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationTerminer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_operation', models.CharField(blank=True, max_length=200, verbose_name="le nom de l'operation")),
                ('date_operation', models.DateTimeField(auto_now_add=True, verbose_name="la date de l'operation")),
                ('nombre_des_agents', models.IntegerField(verbose_name='le nombres des agents')),
                ('agent_fk', models.ManyToManyField(to='agent.Agent', verbose_name='les agents')),
                ('commissariat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lieu_de_travail.commissariat_de_police')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lieu_de_travail.province')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lieu_de_travail.region')),
            ],
        ),
    ]
