# Generated by Django 3.1.7 on 2021-07-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationterminer',
            name='nombre_des_migrants',
            field=models.IntegerField(default=1, verbose_name='le nombres des migrants'),
            preserve_default=False,
        ),
    ]
