# Generated by Django 3.1.7 on 2021-07-22 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_remove_operationterminer_date_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationterminer',
            name='date_operation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="la date de l'operation"),
            preserve_default=False,
        ),
    ]
