# Generated by Django 3.1.7 on 2021-07-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20210722_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationterminer',
            name='nom_operation',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name="le nom de l'operation"),
        ),
    ]
