# Generated by Django 3.2.5 on 2021-08-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_alter_operationterminer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationterminer',
            name='agent_fk',
        ),
    ]
