# Generated by Django 3.2.5 on 2021-08-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_remove_operationterminer_agent_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationterminer',
            name='nature',
            field=models.CharField(choices=[('Terre', 'Terre'), ('Mer', 'Mer')], default='Terre', max_length=30),
            preserve_default=False,
        ),
    ]
