# Generated by Django 3.2.5 on 2021-08-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_operationterminer_nature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationterminer',
            name='nature',
        ),
    ]
