# Generated by Django 3.2.5 on 2021-08-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_remove_operationterminer_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationterminer',
            name='sexe',
            field=models.CharField(choices=[('Terre', 'Terre'), ('Mer', 'Mer')], default=None, max_length=30),
        ),
    ]
