# Generated by Django 3.2.5 on 2021-08-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_operationterminer_sexe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationterminer',
            old_name='sexe',
            new_name='nature_operation',
        ),
    ]
