# Generated by Django 3.2.5 on 2021-08-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrant_irregulier', '0009_remove_migrantirregulier_operation'),
        ('operation', '0014_rename_sexe_operationterminer_nature_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationterminer',
            name='les_migrants',
            field=models.ManyToManyField(to='migrant_irregulier.MigrantIrregulier'),
        ),
    ]
