# Generated by Django 3.2.5 on 2021-08-08 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lieu_de_travail', '0004_auto_20210807_1639'),
        ('operation', '0015_operationterminer_les_migrants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation_Par_Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.ManyToManyField(to='operation.OperationTerminer')),
                ('region_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lieu_de_travail.region')),
            ],
        ),
    ]
