# Generated by Django 3.2.5 on 2021-08-09 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0016_operation_par_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operation_Par_Region',
        ),
    ]
