# Generated by Django 3.2.5 on 2021-08-11 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0017_delete_operation_par_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationterminer',
            name='nombre_des_agents',
        ),
    ]
