# Generated by Django 3.2.5 on 2021-08-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0018_remove_operationterminer_nombre_des_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationterminer',
            name='nombre_des_agents',
            field=models.IntegerField(default=0, verbose_name='le nombres des agents'),
            preserve_default=False,
        ),
    ]
