# Generated by Django 3.2.5 on 2021-09-15 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0019_operationterminer_nombre_des_agents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationterminer',
            name='commissariat',
        ),
    ]
