# Generated by Django 3.1.7 on 2021-07-18 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lieu_de_travail', '0001_initial'),
        ('grade_de_travail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('numero_telephone', models.CharField(max_length=8)),
                ('numero_cin', models.CharField(max_length=8)),
                ('copie_cin', models.ImageField(upload_to='')),
                ('account_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grade_de_travail_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grade_de_travail.gradedetravail')),
                ('lieu_de_travail_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lieu_de_travail.lieu_de_travail')),
            ],
        ),
    ]
