# Generated by Django 3.2.5 on 2021-07-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agent_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
