# Generated by Django 3.1.7 on 2021-07-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_auto_20210729_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='adresse',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='code_postal',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
