# Generated by Django 3.2.5 on 2021-08-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_auto_20210730_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
