# Generated by Django 3.2.5 on 2021-09-15 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_rename_sexe_agent_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='copie_cin',
        ),
    ]
