# Generated by Django 3.2.5 on 2021-09-15 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_remove_agent_copie_cin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='lieu_de_travail_fk',
        ),
    ]
