# Generated by Django 3.1.7 on 2021-07-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_auto_20210723_1929'),
        ('fichier_des_operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier_operation',
            name='operation',
            field=models.ManyToManyField(to='operation.OperationTerminer', verbose_name='les operations'),
        ),
    ]
