# Generated by Django 3.2.5 on 2021-07-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_alter_operationterminer_id'),
        ('fichier_des_operations', '0003_alter_fichier_operation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier_operation',
            name='operation',
            field=models.ManyToManyField(to='operation.OperationTerminer', verbose_name='operation'),
        ),
    ]
