# Generated by Django 3.1.7 on 2021-07-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_de_travail', '0002_alter_gradedetravail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedetravail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
