# Generated by Django 3.1.7 on 2021-07-18 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nationalite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_nationalite', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MigrantIrregulier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('numero_cin', models.CharField(blank=True, max_length=8, verbose_name='le numero cin')),
                ('copie_cin', models.ImageField(blank=True, upload_to='')),
                ('numero_passport', models.CharField(blank=True, max_length=30, verbose_name='le numero de passport')),
                ('copie_passport', models.ImageField(blank=True, upload_to='', verbose_name='copie passport')),
                ('numero_telephone', models.CharField(blank=True, max_length=8, verbose_name='le numero telephone')),
                ('photo_personnel', models.ImageField(blank=True, upload_to='', verbose_name='photo personnel')),
                ('nationalite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='migrant_irregulier.nationalite')),
            ],
        ),
    ]
