# Generated by Django 3.1.7 on 2021-07-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_operationterminer_nombre_des_migrants'),
        ('migrant_irregulier', '0002_auto_20210721_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrantirregulier',
            name='operation',
            field=models.ManyToManyField(to='operation.OperationTerminer'),
        ),
    ]
