# Generated by Django 3.1.7 on 2021-07-21 19:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('migrant_irregulier', '0003_migrantirregulier_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrantirregulier',
            name='capter_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
