# Generated by Django 3.1.7 on 2021-07-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrant_irregulier', '0004_migrantirregulier_capter_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrantirregulier',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
