# Generated by Django 3.2.5 on 2021-07-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrant_irregulier', '0005_migrantirregulier_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrantirregulier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nationalite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
