# Generated by Django 3.1.7 on 2021-07-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrant_irregulier', '0006_auto_20210726_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrantirregulier',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nationalite',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
