# Generated by Django 3.2.5 on 2021-08-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrant_irregulier', '0008_auto_20210807_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrantirregulier',
            name='operation',
        ),
    ]
