# Generated by Django 3.2.5 on 2021-09-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrant_irregulier', '0012_auto_20210915_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrantirregulier',
            name='numero_cin',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='le numero cin'),
        ),
        migrations.AlterField(
            model_name='migrantirregulier',
            name='numero_passport',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='le numero de passport'),
        ),
    ]
